language: cpp
compiler: clang
install:
   - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   - sudo apt-get install qt5-default qtbase5-dev qtdeclarative5-dev qttools5-dev-tools
script: ./build.sh
